# Generated by Django 3.0.7 on 2020-06-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
