# Generated by Django 3.0.7 on 2020-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_like_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
