# Generated by Django 3.0.7 on 2020-06-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0013_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='followed',
        ),
    ]
